package:
  name: openenm
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - setuptools
  - numpy
  run:
  - python
  - setuptools
  - numpy
  - molsysmt
  - pyunitwizard
  - matplotlib
  - tqdm
  - scikit-learn
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'This library...

    '
  dev_url: https://github.com/uibcdf/OpenENM
  doc_url: https://uibcdf.org/OpenENM
