package:
  name: openenm
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - pip
  - setuptools >=61.0
  - versioningit ~=2.0
  run:
  - python
  - pip
  - setuptools >=61.0
  - versioningit ~=2.0
  - molsysmt
  - pyunitwizard
  - matplotlib
  - tqdm
  - scikit-learn
  - lindelint
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'This library...

    '
  dev_url: https://github.com/uibcdf/OpenENM
  doc_url: https://uibcdf.org/OpenENM
