name: Build and upload conda packages

on:
  release:
    types: ['released', 'prereleased']

  workflow_dispatch:

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # do not cancel all in-progress jobs if any job variation fails
      matrix:
        python-version: ["3.8", "3.9", "3.10"] # 3.10 with errors
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup conda env
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: devtools/conda-envs/build_env.yaml
          environment-name: build
          channels: uibcdf, conda-forge, defaults
          extra-specs: |
            python==${{ matrix.python-version }}
      - name: Info conda
        shell: bash -l {0}
        run: |
          micromamba info
          micromamba list
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.2.0
        with:
          meta_yaml_dir: devtools/conda-build
          python-version: ${{ matrix.python-version }}
          mambabuild: false
          platform_linux-64: true
          platform_osx-64: true
          platform_win-64: false
          user: uibcdf
          label: auto
          token: ${{ secrets.ANACONDA_UIBCDF_TOKEN }}

