name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.cfg.os }}, Python ${{ matrix.cfg.python-version }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false  # do not cancel all in-progress jobs if any job variation fails
      matrix:
        #os: ["macOS-latest", "ubuntu-latest"] # windows-latest (https://github.com/openmm/openmm/issues/3618#issuecomment-1166019901)
        #python-version: ["3.8", "3.9", "3.10"]
        cfg:
          - { os: ubuntu-latest, python-version: "3.8"}
          - { os: ubuntu-latest, python-version: "3.9"}
          - { os: ubuntu-latest, python-version: "3.10"}
          - { os: macos-latest,  python-version: "3.8"}
          - { os: macos-latest,  python-version: "3.9"}
          - { os: macos-latest,  python-version: "3.10"}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a


    - name: Setup conda env
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: devtools/conda-envs/test_env.yaml
        environment-name: test
        condarc: |
          channels:
            - uibcdf
            - conda-forge
            - defaults
          channel_priority: strict

        create-args: >-
          python==${{ matrix.cfg.python-version }}

    - name: Install package

      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        python -m pip install . --no-deps

    - name: Info conda
      shell: bash -l {0}
      run: |
        micromamba info
        micromamba list

    - name: Test import module
      shell: bash -l {0}
      run: |
        echo "::group::Importing module from home directory"
        cd
        pwd
        echo 'import openenm; print("Version of the package: {}".format(openenm.__version__))' | python
        echo "::endgroup::"

    - name: Run tests

      # conda setup requires this special shell
      shell: bash -l {0}

      run: |
        pytest -v --cov=openenm --cov-report=xml --color=yes openenm/tests/

    - name: CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.cfg.os }}-py${{ matrix.cfg.python-version }}

