name: Sphinx docs to gh-pages

on:
  release:
    types: ['released']

  workflow_dispatch:

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a

      - name: Setup conda env
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: devtools/conda-envs/docs_env.yaml
          environment-name: docs
          channels: uibcdf, conda-forge, defaults

          extra-specs: |
            python=="3.10"

      - name: Installing the library
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps

      - name: Info conda
        shell: bash -l {0}
        run: |
          micromamba info
          micromamba list

      - name: Test import module
        shell: bash -l {0}
        run: |
          echo "::group::Importing module from home directory"
          cd
          pwd
          echo 'import openenm; print("Version of the package: {}".format(openenm.__version__))' | python
          echo "::endgroup::"

      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v2.0.0

